language: objective-c

before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather

branches:
    only:
        - master
        - develop

osx_image: xcode8
script: xcodebuild clean build -alltargets -project "LEB128.xcodeproj" ONLY_ACTIVE_ARCH=NO | xcpretty
