language: objective-c
branches:
    only:
        - master
        - develop
osx_image: xcode7.3
xcode_project: LEB128.xcodeproj
xcode_scheme: LEB128
xcode_sdk: iphonesimulator9.3
after_success:
- bash <(curl -s https://codecov.io/bash) -J LEB128
