language: objective-c

before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather
after_failure: cat xcodebuild.log
branches:
    only:
        - master
        - develop

osx_image: xcode8
script: xcodebuild -alltargets -project "LEB128.xcodeproj" ONLY_ACTIVE_ARCH=NO | tee xcodebuild.log | xcpretty -f `xcpretty-travis-formatter`
